ktor:
    application:
        modules:
            - com.issueTracker.ApplicationKt.module
    deployment:
        port: 8080

storage:
    driverClassName: "org.postgresql.Driver"
    jdbcURL: "jdbc:postgresql://localhost:5432/postgres?user=admin&password=password"
