ktor:
    application:
        modules:
            - dev.nazmul.issueTracker.authService.ApplicationKt.module
    deployment:
        port: 8080

storage:
    driverClassName: "org.postgresql.Driver"
    jdbcURL: "jdbc:postgresql://auth_service_postgres:5432/postgres?user=admin&password=password"

jwt:
    audience: "jwt-audience"
    issuer: "http://localhost"
    realm: "issueTracker"
    secret: "super_secret"